apiVersion: v1
kind: Service
metadata:
  name: otel-collector
spec:
  selector:
    app: otel-collector
  ports:
    - name: grpc         # Name for gRPC port
      protocol: TCP
      port: 4317          # Expose gRPC port
      targetPort: 4317     # Target port for gRPC
    - name: http          # Name for HTTP port
      protocol: TCP
      port: 55681         # Expose HTTP port
      targetPort: 55681    # Target port for HTTP
  type: ClusterIP         # Internal service
