apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-config
  namespace: default
data:
  tempo.yaml: |
    server:
      http_listen_port: 3100

    storage:
      trace:
        backend: local
        local:
          path: /tmp/tempo

    compactor:
      compaction:
        compacted_block_retention: 48h

    distributor:
      receivers:
        jaeger:
          protocols:
            grpc:
            thrift_binary:
            thrift_compact:
            thrift_http:

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: memberlist
          replication_factor: 1

    querier: {}

    query_frontend: {}
