apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.7.0
        args:
          - "-config.file=/etc/tempo/tempo.yaml"
        volumeMounts:
        - name: tempo-config-volume
          mountPath: /etc/tempo
      volumes:
      - name: tempo-config-volume
        configMap:
          name: tempo-config
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
spec:
  selector:
    app: tempo
  ports:
  - port: 3100
    targetPort: 3100
